version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.0.2

workflows:
  forgetmenot-monorepo-setup:
    jobs:
      - path-filtering/filter:
          filters:
            branches:
              only: main
          base-revision: main
          mapping: |
            services/garden/.* run-garden-service-workflow true
            services/user/.* run-user-service-workflow true
            services/habit/.* run-habit-service-workflow true
            services/auth/.* run-auth-service-workflow true
            services/task/.* run-task-service-workflow true
          config-path: .circleci/monorepo-pipeline-prod.yml
